### ISSUE TITLE
CAMB exit code is always 0 even on failure

### ISSUE THREAD

**Issue by marius311** [cmbant/CAMB#1]
If CAMB is part of a larger script, it'd be useful if it returned non-zero exit code when it failed. 

As far as I can tell, every single invocation of `stop` in the source corresponds to an error. Therefore, a simple search/replace converting all of these to `error stop` should do the trick.

**Comment by cmbant** [comment]
Agreed, now F2008 is more widely supported. Try the "formatted" branch.
