### ISSUE TITLE
Inconstant value of 'ind' on each re-entry to the 'dverk' subroutine

### ISSUE THREAD

**Issue by astralsight5** [cmbant/CAMB#105]
I used the latest release CAMB-1.3.2 to get the matter transfer function. The parameter file is `inifiles/params.ini`. I set `get_scalar_cls=F` and `get_transfer=T`. `number_of_threads` was set to 1 so that I can add extra print statements in the code and get the sequential output. Other items remained unchanged.

The `dverk` subroutine for solving ODEs used by CAMB has an **`ind`** argument. On initial entry `ind` must be set to 1 or 2. For calculating transfer function the subroutine `GetTransfer` initializes `ind` to **1**.
```fortran
      subroutine GetTransfer(EV,tau)
*     ...
*     !initialize ind to 1 
      ind=1
*     ...
      call GaugeInterface_EvolveScal(EV,tau,y,State%Transfer_Times(i),atol,ind,c,w)
*     ...
      end subroutine GetTransfer
```

Later it calls `GaugeInterface_EvolveScal` to evolve the equations. In this subroutine, if `next_switch<tauend` and `next_switch>tau+smallTime` then `dverk` is called indirectly. **`dverk` updates the value of `ind` to 3 after a normal return**.
```fortran
      recursive subroutine GaugeInterface_EvolveScal(EV,tau,y,tauend,tol1,ind,c,w)
*     ...
      if (next_switch < tauend) then
          if (next_switch > tau+smallTime) then
*             !call dverk indirectly. ind is normally updated to 3 after this call
              call GaugeInterface_ScalEv(EV, y, tau,next_switch,tol1,ind,c,w)
*             ...
          end if
*         ...(several if-else branches)
*         !recursive call
          call GaugeInterface_EvolveScal(EV,tau,y,tauend,tol1,ind,c,w)
          return
     end if
     call GaugeInterface_ScalEv(EV,y,tau,tauend,tol1,ind,c,w)
     end subroutine GaugeInterface_EvolveScal
```
Then, here are several if-else branches for different switch types. `ind` is reset to 1 but not in *all* branches. Therefore, **`dverk` may be re-entered with ind=1 or ind=3 in each recursive call to `GaugeInterface_EvolveScal`**. 
```fortran
          if (next_switch == EV%TightSwitchoffTime) then
*             ...
*             !reset ind to 1
              ind=1
*             ...
          else if (next_switch==tau_switch_ktau) then
*             ...(ind is not reset)
          else if (next_switch == tau_switch_nu_massless) then
*             ...(ind is not reset)
          else if (next_switch == tau_switch_nu_nonrel) then
*             ...(ind is not reset)
          else if (next_switch == tau_switch_nu_massive) then
*             ...(ind is not reset)
          else if (next_switch==tau_switch_no_nu_multpoles) then
              ind=1
*             ...
          else if (next_switch==tau_switch_no_phot_multpoles) then
*             ...
              ind=1
*             ...
          else if (next_switch==tau_switch_saha) then
              ind=1
*             ...
          else if (next_switch==tau_switch_evolve_TM) then
              ind=1
*             ...
          end if
*         ...
      end if
```

For test purppose, I added `ind = 1` statement in `GaugeInterface_ScalEv` **to ensure that the value of `ind` is always 1 on each re-entry to `dverk`**. I found there are no difference between the results of the "always ind=1" case and the original one for most k values. Tiny deviation appears at a few k values. For example, the results for k=0.59577521693038948/Mpc (using my parameter setting) are
```
#The original results
#Changeable value of ind on each re-entry to dverk
 EV%q=  0.59577521693038948
 ind=           1
 ind=           3
 ind=           1
 ind=           1
 ind=           1
 ind=           3
 k/h=  0.851107478     transfer_cdm=   104733.180

#"always ind=1" case
#Tiny deviation in transfer function
 EV%q=  0.59577521693038948
 ind=           1
 ind=           1
 ind=           1
 ind=           1
 ind=           1
 ind=           1
 k/h=  0.851107478     transfer_cdm=   104733.164 
``` 
ind=1 and ind=3 are both allowed to re-enter the `dverk` subroutine. Is it a better way to always re-enter `dverk` with ind=1? The other thing I have noticed is that the condition branches in which `ind` is not reset to 1 are all related to neutrino components. Is there any special consideration for this?

**Comment by cmbant** [comment]
Basically it depends on whether the same equations are being stepped in time, or the equations, or number of equations is being changed at a particular step. No bug here?

**Comment by astralsight5** [comment]
I printed out the number of the scalar equations. For  k=0.59577521693038948/Mpc I got the output below
```
 EV%q=  0.59577521693038948     
(tau_start=0.001/EV%q=0.00167848539...)

ind=  1 tau= 1.678485E-03 EV%ScalEqsToPropagate= 32
ind=  3 tau= 3.356971E+01 EV%ScalEqsToPropagate= 24
ind=  1 tau= 8.698965E+01 EV%ScalEqsToPropagate= 32
ind=  1 tau= 3.765924E+02 EV%ScalEqsToPropagate= 29
ind=  1 tau= 6.124727E+02 EV%ScalEqsToPropagate= 19
ind=  3 tau= 1.115320E+03 EV%ScalEqsToPropagate= 19
 k/h=  0.851107478     transfer_cdm=   104733.180
```
On the first entry to the `dverk` ODE solver, `ind` is equal to 1 (the initial value set by `GetTransfer`) and the number of equations is 32. On the second entry, `ind` is not reset to 1 and the number of equations is changed to 24.

I found the following comments in the `dverk` code
> in any event, options may be changed on  re-entry  to  the  subroutine  -  but if the user changes any of the options, or tol, in the course of a calculation he should be careful about  how  such changes affect the subroutine - it may be better to restart with ind = 1 or 2. 
>
In the case here, is it better to reset `ind`?

**Comment by cmbant** [comment]
I think it's OK as along as the remaining equations are consistent with their previous evolution
