### ISSUE TITLE
lensed CMB power spectra using series-expansion method

### ISSUE THREAD

**Issue by catketchup** [cmbant/CAMB#106]
Hello, I was wondering how I can get lensed CMB power spectra using series-expansion method in lensing potential. I would like to get the result in the Fig.8 in https://arxiv.org/abs/astro-ph/0601594

Thank you very much!

**Comment by cmbant** [comment]
You can set camb.config.lensing_method =3 (see https://github.com/cmbant/CAMB/blob/master/fortran/lensing.f90 for numbers, though non-defaults may not have been tested recently)

Please ask questions on CosmoCoffee.info rather than in issues (which are intended for bugs).

**Comment by catketchup** [comment]
Thank you very much!
