### ISSUE TITLE
M1 wrong architecture error on import

### ISSUE THREAD

**Issue by ChiaraMarzano** [cmbant/CAMB#108]
When running my code on Jupyter, I get the following OSError on line "import camb": 

```
OSError: dlopen(/opt/anaconda3/lib/python3.8/site-packages/camb/camblib.so, 6): no suitable image found.  Did find:
	/opt/anaconda3/lib/python3.8/site-packages/camb/camblib.so: mach-o, but wrong architecture
	/opt/anaconda3/lib/python3.8/site-packages/camb/camblib.so: mach-o, but wrong architecture
```

I am working on a Macbook Pro with M1 processor. Please let me know if other details are required.

**Comment by cmbant** [comment]
Installed from conda-forge I assume? I wonder (@beckermr ) if the conda auto-build needs updating for arm macs.

**Comment by beckermr** [comment]
CAMB has not been built for osx-arm on conda-forge yet. Loading it under rosetta may or may not work. IDK.

**Comment by beckermr** [comment]
The build does need updating, but it is a tricky cross-compile and I don't have time to work through it.

**Comment by ChiaraMarzano** [comment]
> Installed from conda-forge I assume? I wonder (@beckermr ) if the conda auto-build needs updating for arm macs.

Yes, I tried both with conda-forge and with pip (I already have gcc installed). I saw a previous issue that seemed to be related  but I checked and the python version I am using is correct so that is not the issue.

Is there any other way I can try to make it run on my machine? 
Thank you

**Comment by beckermr** [comment]
Did you use python for osx-64 or osx-arm? If you want to build from pip, you will need native python I bet, not python running under rosetta. 

I also put in the PR to try and build directly for osx-arm in conda-forge. https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1669

**Comment by cmbant** [comment]
What's the error with pip? (making sure you clean out conda-forge version)

**Comment by beckermr** [comment]
I have the cross-compiled build working here: https://github.com/conda-forge/camb-feedstock/pull/40

I tested it on my local M1 machine and it appears to work. I will merge once I have done the last bit of tests.

**Comment by beckermr** [comment]
Once the PR above merges, wait about 2 hours and then try and install from conda-forge. Assuming you are using the osx-arm64 build, it should work.

**Comment by cmbant** [comment]
Many thanks for sorting that so quickly!

**Comment by lukashergt** [comment]
I had a student run into a similar issue. We fixed it by installing an independent python version (i.e. not using the system python) and setting up a virtualenv. From there pip installing worked fine.
