### ISSUE TITLE
jupyter notebook syntax error

### ISSUE THREAD

**Issue by shan1525** [cmbant/CAMB#109]
Hi everyone , 
I was trying to run the demo notebook of camb  in jupyter notebook, but when I import camb it is giving me the following error:
![camb_error](https://user-images.githubusercontent.com/70058996/126046396-902e2e22-e47f-4460-9d56-aa62ae9d87dd.png)
And if I try to run it in python shell it is working , see below:
![working_python](https://user-images.githubusercontent.com/70058996/126046432-f8fd88d5-7efc-485d-8c29-e792bf45053f.png)
What could be the problem, can anyoneone suggest me the problem here. 

Thanks in advance,
with the best regards,
shan.

**Comment by cmbant** [comment]
With Python 3.6 or higher?

**Comment by shan1525** [comment]
Hi @cmbant , 
Thank you so much for replying. My python version is 3.8.10., gcc version is 9.4. I have all the dependencies updated, but I couldn't figure out the problem. Please, help. 
Thanks in advance, 
With the best regards, 
Shan.

**Comment by cmbant** [comment]
I would make sure the notebook is running the version of python and CAMB that you think it is. The error looks like an old pre-annotation Python version.

**Comment by shan1525** [comment]
Hi @cmbant , 
Thank you so much for looking into this matter. I am very grateful to have your help regarding this. 

With the best regards, 
Shan.
