### ISSUE TITLE
f_K in python

### ISSUE THREAD

**Issue by sjoudaki** [cmbant/CAMB#111]
Hi Antony, for comoving distances in curved space, there is f_K in the Fortran code. Is this quantity perhaps also accessible in the python interface? (to be used in Euclid)

**Comment by cmbant** [comment]
You can get the angular diameter distance if that's what you mean.

**Comment by sjoudaki** [comment]
Yes, sorry about that, for some reason didn't see that the angular diameter distance includes curvature, which is perfectly sufficient (as only factor of 1+z difference with f_K). Many thanks!
