### ISSUE TITLE
camblib.so does not exist

### ISSUE THREAD

**Issue by Rockdeldiablo** [cmbant/CAMB#112]
Hi, i am a new user and i have recentrly tried to install  camb. At first by using conda but then i removed it from there and i used 

`git clone --recursive https://github.com/cmbant/CAMB
python setup.py install`

but when i check` camb --version` i get

```
Library file /home/pasquale/anaconda3/lib/python3.8/site-packages/camb-1.3.4-py3.8.egg/camb/camblib.so does not exist.
Make sure you have installed or built the camb package (e.g. using "python setup.py make"); or remove any old conflicting installation and install again.

```

so i tried `python setup.py make`
 and the answer is 
 
```
running make
Compiling source...
make -C Releaselib --no-print-directory -f../Makefile FORUTILS_SRC_DIR=.. libforutils.a
make[1]: Circular precision.mod <- precision.mod dependency dropped.
make[1]: Circular results.mod <- results.mod dependency dropped.
make[1]: Circular spherbessels.mod <- spherbessels.mod dependency dropped.
make[1]: 'camblib.so' is up to date.
```
so looks like camblib.so is there
but the program still doesn't work. Any advice on how to fix this issue? thanks

**Comment by cmbant** [comment]
Was the first one that failed the conda package?

The "make" build makes it locally in the git repo, not installed, so you'd need to do "pip install -e /path/to/github/version" to install it.

**Comment by Rockdeldiablo** [comment]
> Was the first one that failed the conda package?
 no the conda package gave me a duplicate key error so i removed it with conda remove camb and then i used git clone

apparently there are 2 folders contaning the same files (except camblib.so). the first one is 
`
/home/pasquale/Documents/mcmc/CAMB/camb`

and the second one,  which lack the camblib.so ,file is stored in 

`/home/pasquale/anaconda3/lib/python3.8/site-packages/camb-1.3.4-py3.8.egg/camb`
i think camb search the file in the wrong folder
should i manually remove this second folder?

**Comment by cmbant** [comment]
pip install -e should link the two (removing the second one)

**Comment by Rockdeldiablo** [comment]
> pip install -e should link the two (removing the second one)

thank you, it works.
