### ISSUE TITLE
confusion in the calculation of the bestfit Cls from CAMB

### ISSUE THREAD

**Issue by yashi0195** [cmbant/CAMB#113]
I am trying to obtain the Cls using the values of input parameters from the file ‘base_plikHM_TT_lowl_lowE.minimum’ inside the folder base/plikHM_TT_lowl_lowE/ available on Planck Legacy Archive ‘COM_CosmoParams_fullGrid_R3.01.zip’.
The Cls which are obtained from CAMB are not matching with the Cls in the corresponding ‘base_plikHM_TT_lowl_lowE.minimum.theory_cl’ file.The calculated chi^2 values are also not matching for these 2 cases.

I dont know why this is happening! 
The commands I give are as follows:

>>> import camb
>>> from camb import model, initialpower
>>> import numpy as nm
>>> pars = camb.CAMBparams()
>>> pars.set_cosmology(H0=0.6685791E+02, ombh2=0.2212580E-01, omch2=0.1206815E+00, mnu= 0.6000000E-01, omk=0.0, tau=0.5232887E-01, YHe=0.2400000E+00, TCMB=2.7255)
>>> pars.InitPower.set_params(As=nm.exp(0.3041305E+01)*1e-10, ns=0.9635150E+00, r=0)
>>> pars.set_for_lmax(2500, lens_potential_accuracy=0)
>>> results = camb.get_results(pars)
>>> powers =results.get_cmb_power_spectra(pars, CMB_unit='muK')
>>> totCL=powers['total']
>>> print(totCL)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.01629690e+03  2.96626799e-02  1.71287785e-06  2.59806453e+00]
 ...
 [ 6.89141516e+01  2.94560776e+00  2.33931108e-02 -3.59055928e+00]
 [ 6.87728858e+01  2.94405453e+00  2.33609045e-02 -3.60811776e+00]
 [ 6.86332936e+01  2.94236013e+00  2.33287695e-02 -3.62569176e+00]]

Please help me to understand.
Thanks!

**Comment by cmbant** [comment]
The helium and accuracy parameters look inconsistent.
You can use the camb.set_params_cosmomc function to get CAMB parameter model from Planck chain outputs.
(please post questions like this, rather than bugs, on CosmoCoffee)
