### ISSUE TITLE
matter power spectrum for new dark energy model

### ISSUE THREAD

**Issue by darkfazlollahi** [cmbant/CAMB#114]
Hello guys,

I want to consider the matter power spectrum of the dark energy model with the equation of state such as w=-1+a**a where a is the scale factor. moreover, I want to compare it with the lambda CDM model for this parameter (matter power spectrum).
I do that but I get the error calc_transfer and I don't know how can I solve this problem.
please guide me.

with best

**Comment by cmbant** [comment]
This sounds like a question for CosmoCoffee not a bug for here. But to get some help you'd need to give more specific details about what you are doing and what you have tried doing to debug it.
