### ISSUE TITLE
Option to install CLUSTER_SAFE=1 version by default with pip?

### ISSUE THREAD

**Issue by arahlin** [cmbant/CAMB#116]
Installing with `pip` uses the `CLUSTER_SAFE=0` option for building the shared library.  Is it possible to either change the default, or make it easier to disable the native arch build for installing on a heterogeneous computing cluster?  Something like grabbing the value of the variable from the environment if set, so that `CLUSTER_SAFE=1 pip install camb` does the expected thing.  I'd be happy to submit a PR for this feature if you like.

**Comment by cmbant** [comment]
You can run

`python setup.py make_cluster
`
I'm not sure if there's a way to do this via pip

**Comment by arahlin** [comment]
`pip install --global-option="build_cluster" camb` seems to do the trick.
