### ISSUE TITLE
CAMB unconditionally sets mock_load on ReadTheDocs

### ISSUE THREAD

**Issue by ntessore** [cmbant/CAMB#117]
In `baseconfig.py`, the `mock_load` global that prevents loading of Fortran modules is unconditionally set when CAMB is loaded in a ReadTheDocs environment:

```py
mock_load = os.environ.get('READTHEDOCS', None)
```

Of course, this prevents the documentation from running CAMB on ReadTheDocs even where that is desired, e.g. in code examples.

This situation could be handled by checking instead for e.g. a `CAMB_MOCK_LOAD` environment variable, which can be set where desired.

**Comment by cmbant** [comment]
Is this a problem?
________________________________
From: Nicolas Tessore ***@***.***>
Sent: Tuesday, March 22, 2022 12:09:51 AM
To: cmbant/CAMB ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cmbant/CAMB] CAMB unconditionally sets mock_load on ReadTheDocs (Issue #117)


In baseconfig.py, the mock_load global that prevents loading of Fortran modules is unconditionally set when CAMB is loaded in a ReadTheDocs environment:

mock_load = os.environ.get('READTHEDOCS', None)

Of course, this prevents the documentation from running CAMB on ReadTheDocs even where that is desired, e.g. in code examples.

This situation could be handled by checking instead for e.g. a CAMB_MOCK_LOAD environment variable, which can be set where desired.

**Comment by ntessore** [comment]
It is a problem when one tries to use ReadTheDocs to create demonstrations involving CAMB, e.g. using sphinx-gallery.

This is compounded by the completely obscure error, something along the lines of

    CAMBFortranError: Cannot instantiate CAMBParams, is base class or needs @fortran_class decorator

which to me seemed like the CAMB installation on RTD, even via conda, was broken. Instead it works perfectly once that environment variable is worked around.

**Comment by cmbant** [comment]
I think you are right - it is now possible to build CAMB in readthedocs. These settings were just workarounds for way back when you couldn't. See https://github.com/cmbant/CAMB/commit/7e3fe99ad98ca1dcaeecdc5eab47f5961b9860ec

**Comment by ntessore** [comment]
Great, thanks! To give you data points on CAMB as a dependency, both the conda package and the pip package (using `compilers` from conda) work.
