### ISSUE TITLE
Setting lens_potential_accuracy resets pars.NonLinear

### ISSUE THREAD

**Issue by msyriac** [cmbant/CAMB#118]
I would have expected these two functions to give identical results (the only difference is the order in which pars.NonLinear is set and set_for_lmax is called):

```
import camb
from camb import model

lmax = 3000
H0 = 67.
lens_potential_accuracy = 2

def get_potential():
    pars = camb.CAMBparams()
    pars.set_cosmology(H0=H0)
    pars.InitPower.set_params()
    ##
    pars.set_for_lmax(lmax, lens_potential_accuracy=lens_potential_accuracy)
    ##
    # setting to linear power after setting lens_potential_accuracy
    pars.NonLinear = model.NonLinear_none 
    ##
    results = camb.get_results(pars)
    powers = results.get_lens_potential_cls(lmax)
    return powers[:,0]

def get_potential_reverse():
    pars = camb.CAMBparams()
    pars.set_cosmology(H0=H0)
    pars.InitPower.set_params()
    ##
    # setting to linear power *before* setting lens_potential_accuracy
    pars.NonLinear = model.NonLinear_none
    ##
    pars.set_for_lmax(lmax, lens_potential_accuracy=lens_potential_accuracy)
    ## this seems to reset pars.NonLinear
    results = camb.get_results(pars)
    powers = results.get_lens_potential_cls(lmax)
    return powers[:,0]


cls = get_potential()
cls_rev = get_potential_reverse()

from matplotlib import pyplot as plt
plt.plot((cls_rev[2:]-cls[2:])/cls[2:])
plt.xlabel('$L$')
plt.ylabel(r'$\Delta C_L / C_L$')
plt.savefig('camb_nl_order.png')
```
However, `get_potential_reverse` returns the non-linear lensing power spectrum instead of the linear lensing power spectrum. 

![Screenshot from 2022-04-17 19-42-42](https://user-images.githubusercontent.com/3674397/163736494-14d0242c-a505-41a9-8c75-20dc75f97e89.png)

This specifically happens when `lens_potential_accuracy` is set in `set_for_lmax`. A quick look at the docstrings suggests this may be unintended.

**Comment by msyriac** [comment]
Here's the line of code responsible: https://github.com/cmbant/CAMB/blob/1124228ae0d30a030ec6fb953e4274339206cc2e/camb/model.py#L741

**Comment by msyriac** [comment]
Ok, I see a warning in a docstring here: https://github.com/cmbant/CAMB/blob/1124228ae0d30a030ec6fb953e4274339206cc2e/camb/model.py#L700

But I still feel this is a bit dangerous. Users might want their own default settings in code for lens_potential_accuracy, and they might occasionally want to switch to linear power. Any of these could help: (1) throw a warning when re-setting (2) check if non-linear lensing was already set to False (3) just don't change the non-linear lensing setting when setting lens_potential_accuracy.

**Comment by cmbant** [comment]
I could add "nonlinear=None" as an optional parameter, which defaults to current behaviour but allows you to be explicit?

**Comment by msyriac** [comment]
That sounds good as long as the docstring for set_accuracy makes it clear that nonlinear=None actually means nonlinear=True when lens_potential_accuracy>1. I think my underlying worry is that statements like "self.set_nonlinear_lensing(True)" that internally undo something the user may have set themselves is dangerous.

**Comment by cmbant** [comment]
Try https://github.com/cmbant/CAMB/commit/241c37da74a87bccd80cf0dc0eccf24fdf553d45

**Comment by msyriac** [comment]
Thanks!
