### ISSUE TITLE
Turn off non-linear/halofit when calculating lensing power spectrum in pycamb

### ISSUE THREAD

**Issue by msyriac** [cmbant/CAMB#12]
Is there a way to set `do_nonlinear = 0`  when making calls to pycamb's `get_lens_potential_cls` ?

**Comment by cmbant** [comment]
No, this function just fetches things already calculated. You need to set the non-linear setting when setting up the parameters and calculating the results.

**Comment by msyriac** [comment]
Understood. I see now from the demo notebook that I can use `pars.NonLinear = model.NonLinear_none`  but it isn't obvious from the documentation itself that one can do this. It might be nice to have it as an argument passed to, say, `camb.model.CAMBParams.set_matter_power` .

Thanks!

**Comment by cmbant** [comment]
Commit 0d2ed77da8978b70d638c6e6635ff6d34774aade adds a nonlinear parameter to set_matter_power, and  a separate set_nonlinear_lensing function. See
http://camb.readthedocs.io/en/latest/model.html#camb.model.CAMBparams.set_matter_power
