### ISSUE TITLE
Choosing resolution in z and k for ISW integral

### ISSUE THREAD

**Issue by AvivTheMan** [cmbant/CAMB#121]
I am working with CAMB as implemented in CosmoMC, specifically in the Modified Gravity extension ISiTGR. I have been investigating an issue regarding the CMB temperature-temperature correlation spectrum (the TT Cls) when varying a specific modified gravity parameter, and have narrowed it down to most likely having something to do with the "resolution" of points in redshift z and scale k when integrating to obtain Delta{T}/T for the Integrated Saches-Wolfe effect.

In `camb/fortran/equations.f90`, the ISW component of the CMB OutputSources is essentially just the time-derivative of the Weyl potential, which is later integrated as a function of redshift (and indirectly as a function of scale k). I cannot figure out how the points in z and k at which the ISW integrand is computed are chosen, whether there is an algorithm somewhere in CAMB that decides how they are chosen, and if there is some parameter somewhere that controls this (eg. a parameter that determines the spacing in z or k, or how much interpolation occurs, or the regions where a higher density of points is required). Additionally, tracing through the CAMB code, I am having trouble finding where the ISW integrand (the time-derivative of the Weyl potential) is integrated to give Delta{T}/T, and the subsequent calculation for transforming this into a correlation coefficient Cl.

Any help would be greatly appreciated, and would aid in resolving this issue!

**Comment by cmbant** [comment]
This seems not to be a bug in the main code, so please post on CosmoCoffee instead

**Comment by AvivTheMan** [comment]
Okay, sorry about that. Thanks!
