### ISSUE TITLE
Issues with running camb

### ISSUE THREAD

**Issue by OladimejiDurosaro** [cmbant/CAMB#122]
Hello, I am getting the error message below when I run Camb on jupyter notebook.

OSError: dlopen(/Users/oladimejidurosaro/opt/anaconda3/lib/python3.9/site-packages/camb/camblib.so, 0x0006): tried: '/Users/oladimejidurosaro/opt/anaconda3/lib/python3.9/site-packages/camb/camblib.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

Kindly assist.

**Comment by cmbant** [comment]
Looks like you have python versions/builds mixed up. Was CAMB installed via conda?

**Comment by OladimejiDurosaro** [comment]
Yes, it was installed via conda using the terminal.
Please what do you suggest I do to resolve this.

**Comment by cmbant** [comment]
I assume you don't have an M1 mac. I don't use a Mac myself, so no idea really. It doesn't sound like a CAMB issue. 
Lots of similar on Google, e.g https://stackoverflow.com/questions/71247107/mach-o-file-but-is-an-incompatible-architecture-have-arm64-need-x86-64

**Comment by OladimejiDurosaro** [comment]
I am using an M1 mac and I have searched google but seem not to have found a way around it yet.

**Comment by cmbant** [comment]
I would try making a new clean anaconda environment and installing there
