### ISSUE TITLE
Demo stops running at In [55] because of a TypeError

### ISSUE THREAD

**Issue by IamSreeman** [cmbant/CAMB#123]
Somehow I am getting this error even though the same demo file on binder is running without any issue. I definitely did not remove 2 arguments inside `camb.set_params()`.

```
TypeError                                 Traceback (most recent call last)
Input In [55], in <cell line: 21>()
     18 axs[1].plot(cl_LCDM[2:,0])
     20 # Set dark energy fraction 0.1 at z=1e4
---> 21 pars = camb.set_params( ombh2=0.022, omch2=0.122, 
     22                        w_n=(n-1.)/(n+1.),  theta_i=np.pi/2, zc = 1e4, fde_zc = 0.1,
     23                        dark_energy_model='AxionEffectiveFluid', thetastar=thetastar) #
     24 results = camb.get_results(pars)
     25 print('AxionEffectiveFluid: h0 = ', results.Params.H0)

File ~/anaconda3/lib/python3.9/site-packages/camb/camb.py:156, in set_params(cp, verbose, **params)
    154 do_set(cp.set_accuracy)
    155 do_set(cp.set_classes)
--> 156 do_set(cp.DarkEnergy.set_params)
    157 do_set(cp.set_cosmology)
    158 do_set(cp.set_matter_power)

File ~/anaconda3/lib/python3.9/site-packages/camb/camb.py:150, in set_params.<locals>.do_set(setter)
    148 if verbose:
    149     logging.warning('Calling %s(**%s)' % (setter.__name__, kwargs))
--> 150 setter(**kwargs)

TypeError: set_params() missing 2 required positional arguments: 'om' and 'a_c'

```

![image](https://user-images.githubusercontent.com/62174391/176066312-ed89f1f9-41ff-4e19-b832-334584a2763e.png)

**Comment by cmbant** [comment]
I would check you are running the version of CAMB that you think you are.

**Comment by IamSreeman** [comment]
@cmbant you are right, I used `conda install -c conda-forge camb` but it installed old `1.1.3`. When I tried to install by specifying the version as `1.3.5` it is an environment failure. CAMB can be used on binder but Cobaya can't be used on binder right?

**Comment by IamSreeman** [comment]
@cmbant I want to add a correction term to the Friedmann equation with a single parameter. The only place where you used the Friedmann equation is [symbolic.py](https://github.com/cmbant/CAMB/blob/master/camb/symbolic.py). Apart from changing that the only other change needed is in the [model.f90 file](https://github.com/cmbant/CAMB/blob/master/fortran/model.f90) (to add a new parameter) right? Sorry for asking here, but [cosmocoffee](https://cosmocoffee.info/) is not allowing my username.

**Comment by cmbant** [comment]
Well it will be more complicated if you are changing the change affects the perturnations.

**Comment by IamSreeman** [comment]
@cmbant will it be simpler in CosmoMC or will it be same? In arXiv:1907.05344 (astro-ph) they used CosmoMC for a Generalized Chaplygin gas model, which is also not a common model.

**Comment by cmbant** [comment]
Cobaya and Cosmomc just use CAMB. Chalygin gas models is not something I can help with.
