### ISSUE TITLE
 PowerSpectrumInterpolator  Error

### ISSUE THREAD

**Issue by thegreenarowa** [cmbant/CAMB#126]
Hi, I am getting the  "PowerSpectrumInterpolator " error. I am attaching the screenshot of the error. Please help

![image](https://user-images.githubusercontent.com/72656628/181829356-0469646d-d9f7-4630-98ec-0aee4257bd6d.png)
![camb_err](https://user-images.githubusercontent.com/72656628/181829407-6fc5764a-00c3-46f4-a914-a254cc2987b0.png)

**Comment by cmbant** [comment]
You really need to give more details about what you are doing and why the error message is not correct (e.g. a likelihood is calling the power spectrum for too high k).

**Comment by thegreenarowa** [comment]
Hi here is the YAML file which is generating such an error.

[Nonlinearfluidbase+des+H0.txt](https://github.com/cmbant/CAMB/files/9316934/Nonlinearfluidbase%2Bdes%2BH0.txt)

**Comment by cmbant** [comment]
That looks like a Cobaya yaml file. This is the CAMB repo, for a CAMB bug I really need a reproducible CAMB-only piece of code to reproduce a bug. (the error message looks to me as though it may be correct, it depends on what you are doing in Cobaya).
