### ISSUE TITLE
macOS Monterey installation issue (not M1 chip)

### ISSUE THREAD

**Issue by lisaleemcb** [cmbant/CAMB#129]
Hello! I forked the repo and am trying to install an editable version of CAMB on my machine. However, I'm getting an error, of which the relevant part I believe is:

 ```
   ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
    collect2: error: ld returned 1 exit status
    make[2]: *** [Releaselib/camblib.so] Error 1
    make[1]: *** [camblib.so] Error 2
    make: *** [python] Error 2
    chmod: ../camb/camblib.so: No such file or directory
    Compilation failed
    Compiling source...
    [end of output]
```

I tried the suggested fix floating around the internet à la [this](https://stackoverflow.com/questions/63592445/ld-unsupported-tapi-file-type-tapi-tbd-in-yaml-file) but it doesn't work me.  Any suggestions would be appreciate, thank you!

**Comment by cmbant** [comment]
May be a gfortran conflict or similar? https://github.com/llvm/llvm-project/issues/55836
If in doubt I'd start with a clean new python environment

**Comment by lisaleemcb** [comment]
Apologies- the suggested fortran fix didn't solve my problem.  I also tried a clean python env, but I think my current versions are not compatible with CAMB. Do you have a list of non-problematic versions of the dependencies? I only see sympy and scipy in the requirements file.

**Comment by cmbant** [comment]
Can you compile any other fortran programs? (I assume you installed gfortran, check gfortran --version) 
If not this looks like a Mac config issue.

**Comment by lisaleemcb** [comment]
Took your suggestion of creating a clean conda env and it installed this way.  Thanks for your help!
