### ISSUE TITLE
python3 setup.py make fails: /camb/camblib.so: No such file

### ISSUE THREAD

**Issue by tishuea** [cmbant/CAMB#130]
Hi,

I have compiled the fortran code. I successfully run camb inifiles/planck_2018.ini.

Now, I try python3 setup.py and receive this message: 

CAMB-1.3.5 % python3 setup.py make        
running make
Compiling source...
make: *** No rule to make target `f', needed by `python'.  Stop.
chmod: ../camb/camblib.so: No such file or directory
Compilation failed

Any help with this would be much appreciated!

**Comment by cmbant** [comment]
Sounds odd, does normall pip install -e work? Might be helpful to track down exactly where that error is coming from.

**Comment by cmbant** [comment]
Did you figure out what this is?

**Comment by tishuea** [comment]
Hi Antony,

Apologies for the slow reply. I did not figure out this particular issue, but I tried instead installing directly from git and things seem to be working now. Please feel free to close this. Thank you.

Best,
Avery

**Comment by cmbant** [comment]
OK thanks.
