### ISSUE TITLE
Is nonlinear Pk renormalized outside of the nonlinear halofit.f90 module

### ISSUE THREAD

**Issue by MinhMPA** [cmbant/CAMB#132]
Hi,

As I'm going into the nonlinear [halofit.f90](https://github.com/cmbant/CAMB/blob/master/fortran/halofit.f90) fortran module to modify the 2-halo term, specifically linearly rescaling the linear P(k,z!=0) that it takes as input. I encounter something that looks like a (re-)normalization to the nonlinear power spectrum outside of `halofit.f90`. Namely, no matter _how_ I (linearly) rescale the linear P(k,0) to a given P(k,z!=0), the output only change at high-k regime.

I have narrowed the issue down by simply setting
`pfull=p2h`
inside the subroutine `halomod()`
and
`p_2h=plin`
inside the function `p_2h()`.

I then expect the output nonlinear P(k,z) to be just the linear P(k,z), which I confirm that it is, and linearly shifted for different `plin`. The `plin` are normalized to the standard CAMB output at z=0 and differ for different cosmologies with different D(z).

However, the output of
```
cosmo_params.NonLinear = model.NonLinear_both
results.calc_power_spectra(cosmo_params)
kh_nonlin, z_nonlin, pk_nonlin_LCDM = results.get_matter_power_spectrum(minkh=kmin, maxkh=kmax, npoints = 200)
```
stay numerically the same for two different `plin`. I ensure the two `plin` are actually different by flushing them and their ratio to standard output.

My question is: is there anything done to pfull output from `halofit.f90` before CAMB outputs it as above? I would like to limit my modifications within the nonlinear halofit module, if possible.

**Comment by cmbant** [comment]
Halofit returns the ratio of the nonlinear to the linear spectrum, if that what you mean? (e.g. for imead=3, line 622)

**Comment by MinhMPA** [comment]
@cmbant Thank you! That's the insider's insight I was indeed looking for.

So just to verify before closing this issue: the nonlinear `halofit` module computes the nonlinear Pk internally and only passes to CAMB the `CAMB_Pk%nonlin_ratio`, which is then multiplied by the linear Pk (also stored in `CAMB_Pk`) to result in the final nonlinear Pk output?

**Comment by cmbant** [comment]
Right
