### ISSUE TITLE
HMcode-2020 problem with feedback at low k

### ISSUE THREAD

**Issue by alexander-mead** [cmbant/CAMB#135]
It has been bought to my attention that there is a small problem with the HMcode-2020 feedback recipe at low k. Baryonic feedback should have a negligible effect on P(k) for k < 1e-2 h/Mpc, however, the HMcode-2020 feedback model erroneously predicts ~10% level effects at k = 1e-4 h/Mpc.

This is a bug, which I have now fixed. The before and after can be seen here:

Before:
![before](https://user-images.githubusercontent.com/9140961/211589292-1b303b07-74b0-49bf-aae6-51dfc0de750f.png)
After:
![after](https://user-images.githubusercontent.com/9140961/211589414-ce0e428a-2d0d-43c6-b3dc-dca78bb084bd.png)

Are you able to give me permission to push my new branch, with the correction, to the CAMB repository? I think you can do this while protecting the master branch.

**Comment by cmbant** [comment]
Thanks - just generate a pull request from your own site? Usually easiest.
