### ISSUE TITLE
Unexpected segmentation fault

### ISSUE THREAD

**Issue by kumarutkarsh641** [cmbant/CAMB#137]
Hi, I am facing a segmentation fault while using Planck with the BAO and other data-set. I am pasting the error file here
please have a look.

[cn170-35:28944] *** Process received signal ***
[cn170-35:28944] Signal: Segmentation fault (11)
[cn170-35:28944] Signal code: Address not mapped (1)
[cn170-35:28944] Failing at address: 0xc
[cn170-35:28944] [ 0] /lib64/libpthread.so.0(+0xf630)[0x2b8e7caf0630]
[cn170-35:28944] [ 1] /home/kumaru/cobayacode/code/CAMB/camb/camblib.so(__cambmain_MOD_cltransfertocl+0x1420)[0x2b8ebf471390]
[cn170-35:28944] [ 2] /home/kumaru/cobayacode/code/CAMB/camb/camblib.so(__camb_MOD_camb_transferstopowers+0x286)[0x2b8ebf4845b6]
[cn170-35:28944] [ 3] /home/management/apps/gcc/9.3.0/lib64/libffi.so.8(+0x8052)[0x2b8e8898d052]
[cn170-35:28944] [ 4] /home/management/apps/gcc/9.3.0/lib64/libffi.so.8(+0x6c95)[0x2b8e8898bc95]
[cn170-35:28944] [ 5] /home/management/apps/python/3/3.9.6/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so(+0x136bf)[0x2b8e887796bf]
[cn170-35:28944] [ 6] /home/management/apps/python/3/3.9.6/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so(+0x8421)[0x2b8e8876e421]
[cn170-35:28944] [ 7] /home/management/apps/python/3/3.9.6/bin/python3.9(_PyObject_MakeTpCall+0x7a)[0x4d85ca]
[cn170-35:28944] [ 8] /home/management/apps/python/3/3.9.6/bin/python3.9(_PyEval_EvalFrameDefault+0x4b0a)[0x54734a]
[cn170-35:28944] [ 9] /home/management/apps/python/3/3.9.6/bin/python3.9[0x541c69]
[cn170-35:28944] [10] /home/management/apps/python/3/3.9.6/bin/python3.9(_PyFunction_Vectorcall+0x195)[0x4d8f25]
[cn170-35:28944] [11] /home/management/apps/python/3/3.9.6/bin/python3.9(_PyEval_EvalFrameDefault+0x621)[0x542e61]
[cn170-35:28944] [12] /home/management/apps/python/3/3.9.6/bin/python3.9[0x5422ef]
[cn170-35:28944] [13] /home/management/apps/python/3/3.9.6/bin/python3.9(_PyFunction_Vectorcall+0x195)[0x4d8f25]
[cn170-35:28944] [14] /home/management/apps/python/3/3.9.6/bin/python3.9[0x58a881]
[cn170-35:28944] [15] /home/management/apps/python/3/3.9.6/bin/python3.9(PyObject_Call+0x144)[0x4da214]
[cn170-35:28944] [16] /home/management/apps/python/3/3.9.6/bin/python3.9(_PyEval_EvalFrameDefault+0x314a)[0x54598a]
[cn170-35:28944] [17] /home/management/apps/python/3/3.9.6/bin/python3.9[0x541c69]
[cn170-35:28944] [18] /home/management/apps/python/3/3.9.6/bin/python3.9(_PyFunction_Vectorcall+0x195)[0x4d8f25]
[cn170-35:28944] [19] /home/management/apps/python/3/3.9.6/bin/python3.9[0x58a881]
[cn170-35:28944] [20] /home/management/apps/python/3/3.9.6/bin/python3.9(_PyEval_EvalFrameDefault+0x1160)[0x5439a0]
[cn170-35:28944] [21] /home/management/apps/python/3/3.9.6/bin/python3.9[0x5422ef]
[cn170-35:28944] [22] /home/management/apps/python/3/3.9.6/bin/python3.9(_PyFunction_Vectorcall+0x195)[0x4d8f25]
[cn170-35:28944] [23] /home/management/apps/python/3/3.9.6/bin/python3.9[0x58a881]
[cn170-35:28944] [24] /home/management/apps/python/3/3.9.6/bin/python3.9(_PyEval_EvalFrameDefault+0x1160)[0x5439a0]
[cn170-35:28944] [25] /home/management/apps/python/3/3.9.6/bin/python3.9[0x541c69]
[cn170-35:28944] [26] /home/management/apps/python/3/3.9.6/bin/python3.9(_PyFunction_Vectorcall+0x195)[0x4d8f25]
[cn170-35:28944] [27] /home/management/apps/python/3/3.9.6/bin/python3.9(_PyEval_EvalFrameDefault+0x621)[0x542e61]
[cn170-35:28944] [28] /home/management/apps/python/3/3.9.6/bin/python3.9(_PyFunction_Vectorcall+0xfb)[0x4d8e8b]
[cn170-35:28944] [29] /home/management/apps/python/3/3.9.6/bin/python3.9[0x58a881]
[cn170-35:28944] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 23 with PID 0 on node cn170-35 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

**Comment by cmbant** [comment]
Odd, don't think I've seen that before. If you can isolate this to a single model that reliably reproduces the error, please add a code example to reproduce it.

**Comment by kumarutkarsh641** [comment]
sorry, I did not understand. can you please elaborate ? thank you

**Comment by cmbant** [comment]
e.g. a short camb-only example notebook at that loads the problem parameters and reproduces the issue using CAMB directly.

**Comment by kumarutkarsh641** [comment]
Here it is .
![1AD59345-0B5A-47AE-8B87-C7C10B53CF89](https://user-images.githubusercontent.com/70899088/215256866-8867b683-12e7-4625-8f52-2dbfc9f7dcab.jpeg)

**Comment by cmbant** [comment]
DarkParamFluid does not look like a standard CAMB component, so the issue probably lies there. Otherwise please could you post a full reproducing notebook or .py file.

**Comment by cmbant** [comment]
Closing as no response.
