### ISSUE TITLE
modifying dtauda in equations.f90

### ISSUE THREAD

**Issue by kumarutkarsh641** [cmbant/CAMB#138]
Hi, I want to modify the dtauda function in equation.f90.  I want to multiply the RHS of dtauda by a prefactor, a function of 
scale factor, and an additional parameter epsilon. Can anyone let me know which files I need to modify except equation.f90? I am new to camb. Any help is highly appreciated.
Thanks

**Comment by cmbant** [comment]
Please ask questions on cosmocoffee, this is for bugs
