### ISSUE TITLE
Dverk error -3:

### ISSUE THREAD

**Issue by kumarutkarsh641** [cmbant/CAMB#139]
Hi, I have modified the definition of adotoa in the equation.f90 module. After modification, I am getting this error when I try results = camb.get_results(pars)

---------------------------------------------------------------------------
CAMBError                                 Traceback (most recent call last)
Cell In[10], line 1
----> 1 results = camb.get_results(pars)

File ~/CAMB/camb/camb.py:35, in get_results(params)
     33 if _debug_params:
     34     print(params)
---> 35 res.calc_power_spectra(params)
     36 return res

File ~/CAMB/camb/results.py:333, in CAMBdata.calc_power_spectra(self, params)
    326 """
    327 Calculates transfer functions and power spectra.
    328 
    329 :param params: optional :class:`~.model.CAMBparams` instance with parameters to use
    330 
    331 """
    332 if params is not None:
--> 333     self.calc_transfers(params, only_transfers=False)
    334 else:
    335     self._check_powers()

File ~/CAMB/camb/results.py:315, in CAMBdata.calc_transfers(self, params, only_transfers, only_time_sources)
    312     self._check_powers(params)
    313 if CAMBdata_gettransfers(byref(self), byref(params), byref(c_int(1 if only_transfers else 0)),
    314                          byref(c_int(1 if only_time_sources else 0))):
--> 315     config.check_global_error('calc_transfer')

File ~/CAMB/camb/_config.py:51, in _config.check_global_error(self, reference)
     49     reference = ''
     50 if err:
---> 51     raise CAMBError(reference + '%s' % err)
     52 else:
     53     raise CAMBError(reference + 'Error code: %s' % code)

CAMBError: Error in Fortran called from calc_transfer:
Dverk error -3: the subroutine was unable  to  satisfy  the  error requirement  with a particular step-size that is less than or * equal to hmin, which may mean that tol is too small--- but most likely you've messed up the y array indexing; compiling with bounds checking may (or may not) help find the problem.

However, there is no error in getting background results. Please help me in this regard

**Comment by cmbant** [comment]
If you have modified the code, it is not a bug in this repository.
