### ISSUE TITLE
Change to Planck likelihood values when going from camb 1.3 to 1.4

### ISSUE THREAD

**Issue by joezuntz** [cmbant/CAMB#140]
Hi Antony,

My continuous integration tests picked up that the value of the Planck likelihood changed by Delta(logL) ~ 3 for some vaguely fiducial values of the cosmological parameters when updating from camb v1.3.x to v1.4.

I just wanted to ask if this is expected, and not some symptom of me using camb incorrectly in cosmosis?  I saw that various constants changed so I guess this is as expected, but wanted to check with you to be sure.

Cheers,
Joe

**Comment by cmbant** [comment]
Delta of 3 is getting quite big, but chi2 can change a lot for quite small changes in the spectra. Constants changed, default nnu changed, and HMcode bug was fixed (affecting low k). I don't recall seeing changes as large as 3 for just Planck likelihoods when updating Cobaya's tests.

**Comment by joezuntz** [comment]
Thanks for this - I've tracked things down to the fact that my parameters were a really long way from the Planck best fit. When I swtich to best-fit paramters the change goes down to log(L) ~ 0.1, which seems fine.
