### ISSUE TITLE
Search in online documentation not working

### ISSUE THREAD

**Issue by JCGoran** [cmbant/CAMB#142]
The search over at https://camb.readthedocs.io/ does not seem to be working; when I make a query with a term that I am certain should exist (like searching for `set_params`), the search never finishes.
For what it's worth, the browser console reports (not sure if it has any relevance for the issue):

```plaintext
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://camb.readthedocs.io/en/latest/search.html?q=omch2&check_keywords=yes&area=default#:288
[search.html:288:7](https://camb.readthedocs.io/en/latest/search.html?q=omch2&check_keywords=yes&area=default#)
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://camb.readthedocs.io/en/latest/search.html?q=omch2&check_keywords=yes&area=default#:296
[search.html:296:5](https://camb.readthedocs.io/en/latest/search.html?q=omch2&check_keywords=yes&area=default#)
JQuery not found. Injecting. [readthedocs-doc-embed.js:1:32507](https://camb.readthedocs.io/_/static/javascript/readthedocs-doc-embed.js)
```

**Comment by JCGoran** [comment]
I dunno which Sphinx version is used internally by readthedocs, but in the [v6 release notes](https://blog.readthedocs.com/sphinx6-upgrade/) there's this tidbit:

> Bundled jQuery is removed. The JavaScript asset is easily added back using the new extension [sphinxcontrib-jquery](https://pypi.org/project/sphinxcontrib.jquery/). It is included automatically by [sphinx-rtd-theme](https://sphinx-rtd-theme.readthedocs.io/), so if you are using our theme, you will also continue to have jQuery available in your documentation.

so maybe adding `"sphinxcontrib.jquery"` and/or `"sphinx_rtd_theme"` to the `extensions` variable in `conf.py` should do the trick?

**Comment by cmbant** [comment]
Thanks, looks like adding sphinx_rtd_theme and sphinxcontrib.jquery may have done the trick

**Comment by JCGoran** [comment]
Seems to be fixed now, thanks!
