### ISSUE TITLE
Installation in clean environment broken due to missing 'packaging'

### ISSUE THREAD

**Issue by steven-murray** [cmbant/CAMB#148]
A recent update seems to have broken the installation process, since the installation requires the `packaging` package, which is not installed by default. Thus installing into a fresh environment breaks. I can get around this in my own package (which depends on `camb` by adding `packaging` to the `build-system.requires` list of the `pyproject.toml`, but it might be good to fix this in the `camb` package itself.

**Comment by steven-murray** [comment]
Scratch that -- my CI builds for `hmf` are still not working even after adding `packaging` to my pyproject.toml, so it seems this will have to be fixed in the `camb` package directly.

**Comment by cmbant** [comment]
packaging is a requirement in setup.py, and is only used dynamically. On my system it installs OK with packaging uninstalled.
(assuming you are talking about latest 1.5.1 or master?)

The conda build is not currently updated due to some issue I'm not sure how to fix.

**Comment by steven-murray** [comment]
Interesting -- my failing build is here: https://github.com/halomod/hmf/actions/runs/6391301315/job/17346279891?pr=195. 

`packaging` is used dynamically, but is called from the `setup.py` here:

```
        File "/tmp/pip-install-wo7p4a2r/camb_31b49620b7f647f8ae4a4ee6d0c040dd/camb/_compilers.py", line 40, in check_gfortran
          from packaging.version import parse as parse_version
```

**Comment by steven-murray** [comment]
Just confirmed locally that this fails:

```
conda create -n tmp python=3.11
conda activate tmp
pip install camb
```

whereas

```
conda create -n tmp python=3.11
conda activate tmp
pip install packaging
pip install camb
```

does work.

**Comment by cmbant** [comment]
Interesting, pip install -e from source does work, but from pypi (or without -e) does not. I've added a simple pyproject.toml with the build requirements, hopefully this fixes it?

**Comment by steven-murray** [comment]
This has fixed my CI builds, thank you!
