### ISSUE TITLE
Issue installing CAMB on cluster

### ISSUE THREAD

**Issue by vittoriodx7** [cmbant/CAMB#150]
Hello,
I am trying to install CAMB on a cluster. 
If I log-in, load my conda environment, and then install it normally using `pip install camb` there are no issue at all. However I need to install it after loading several modules for consistency of consequent runs, e.g. parallelization using MPI.
Therefore I first load the required modules:
`module load intel/21.7.1 impi/2021.7`
just some intel basics and intel MPI.
but after this when I try to install camb using  `pip install camb` I get the following message:

Building wheels for collected packages: camb
  Building wheel for camb (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
```
  × Building wheel for camb (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_py
      /bin/sh: line 0: test: too many arguments
      /bin/sh: line 0: test: too many arguments
      /bin/sh: line 0: test: too many arguments
      /bin/sh: line 0: test: too many arguments
      make -C Releaselib --no-print-directory -f../Makefile FORUTILS_SRC_DIR=.. libforutils.a
      /bin/sh: -c: line 0: unexpected EOF while looking for matching `''
      /bin/sh: -c: line 1: syntax error: unexpected end of file
      make[3]: *** [../Makefile:49: compiler.ver] Error 1
      make[2]: *** [Makefile:69: directories] Error 2
      make[1]: *** [Makefile:29: Releaselib] Error 2
      make: *** [Makefile_main:141: libforutils_so] Error 2
      chmod: cannot access '../camb/camblib.so': No such file or directory
      Compiling source...
      Compilation failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for camb
Failed to build camb
ERROR: Could not build wheels for camb, which is required to install pyproject.toml-based projects
```

What do you suggest checking here? Can I proceed safely and install CAMB before loading the parallelization modules mentioned above?

Thanks,
Vittorio

**Comment by cmbant** [comment]
I guess it is now trying to build using ifort rather than gfortran. Try running the make command directly and maybe adding debug option to see more info. (you may be able to just install camb before loading intel)

**Comment by vittoriodx7** [comment]
Thanks a lot for the reply! I tried your suggestion and it worked. 
I then fixed the installation from scratch.
Below the code I used, note that I basically forced make to  skip ifort compiler because option 7 is not available

```
module load intel/21.7.1 -v
module load impi/2021.7 -v

conda create -n myenv python=3.8
conda activate myenv

pip install scipy packaging
git clone --recursive https://github.com/cmbant/CAMB.git
cd CAMB
sed -i -e 's/ifeq "$(ifortErr)" "0"/ifeq "$(ifortErr)" "7"/g' fortran/Makefile
sed -i -e 's/ifeq "$(ifortErr)" "0"/ifeq "$(ifortErr)" "7"/g' forutils/Makefile_compiler
python setup.py install

```
