### ISSUE TITLE
Broken Makefile when using Intel compiler

### ISSUE THREAD

**Issue by AndreaPezzotta** [cmbant/CAMB#153]
I am trying to install CAMB on a cluster using ifort (from one of the modules available on the cluster). If I try to clone the CAMB repository (`git clone --recursive https://github.com/cmbant/CAMB`) and install the fortran code using the Makefile, I get the following output:

```
>>> make
/bin/sh: line 0: test: too many arguments
/bin/sh: line 0: test: too many arguments
/bin/sh: line 0: test: too many arguments
/bin/sh: line 0: test: too many arguments
make -C Release --no-print-directory -f../Makefile FORUTILS_SRC_DIR=.. libforutils.a
/bin/sh: -c: line 0: unexpected EOF while looking for matching `''
/bin/sh: -c: line 1: syntax error: unexpected end of file
../Makefile:49: recipe for target 'compiler.ver' failed
make[3]: *** [compiler.ver] Error 1
Makefile:68: recipe for target 'directories' failed
make[2]: *** [directories] Error 2
Makefile:26: recipe for target 'Release' failed
make[1]: *** [Release] Error 2
Makefile_main:145: recipe for target 'libforutils' failed
make: *** [libforutils] Error 2
```

I am using version 21.7.1 of Intel for this, but I tried also with other versions, like version 18.0.5, and I get the same error. If I use a gnu compiler everything works fine, but I need to have CAMB installed with ifort because of other dependencies.

**Comment by cmbant** [comment]
Not sure, run make with more verbose output to see what it is objecting to. (and "which make" running the right program)
(maybe start compiling just forutils)

**Comment by cmbant** [comment]
I can't reproduce any generic problem with ifort. Perhaps using wrong "make"/"gmake"
