### ISSUE TITLE
Segmentation fault when compiling

### ISSUE THREAD

**Issue by energy-berkeley** [cmbant/CAMB#18]
Hi,
I cloned the newest version of the code and tried to compile with make. But I got the error:
camb_python.f90: In function ‘convert_cltransferdata’:
camb_python.f90:153:0: internal compiler error: Segmentation fault
         cData%q = c_loc(data%q%points)
Do you think it is a compiler version problem? How can I remedy this?
Thanks a lot.
MC

**Comment by cmbant** [comment]
Yes, internal compiler errors a are by definition compiler bugs. Which compiler version are you using?

**Comment by energy-berkeley** [comment]
GNU Fortran (GCC) 4.8.5

**Comment by cmbant** [comment]
I think you need at least 4.9
