### ISSUE TITLE
CAMB with OpenMP segfaults on Alpine Linux

### ISSUE THREAD

**Issue by marius311** [cmbant/CAMB#24]
On Alpine Linux (which uses musl instead of glibc) if I use OpenMP I get a segfault when running CAMB. I really have no idea if this is in anyway CAMB's fault, or if perhaps an easy CAMB workaround could be found, but if there was a way to make this work this would be useful (to me at least) since Alpine Linux is a standard Docker base image for making small images. 

Here's a Dockerfile you can use to reproduce the error, 
```Dockerfile
FROM alpine:edge

RUN apk add --update curl gfortran make musl-dev \
    && mkdir -p /root/camb \
    && curl -L https://github.com/cmbant/camb/tarball/f5ffb9a | tar zxf - -C /root/camb --strip-components=1 \
    # && sed -i -e "s/-fopenmp//g" /root/camb/Makefile \
    && cd /root/camb \
    && make
```

Then run the container and just run `./camb params.ini` to see the segault. Uncomment the commented line above to compile without openmp and it works. Here's the backtrace from gdb, btw:

```
Thread 8 "camb" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 25]
0x000055555559c651 in __gaugeinterface_MOD_gaugeinterface_evolvescal ()
(gdb) where
#0  0x000055555559c651 in __gaugeinterface_MOD_gaugeinterface_evolvescal ()
#1  0x000055555559ca5d in __gaugeinterface_MOD_gaugeinterface_evolvescal ()
#2  0x000055555559ca5d in __gaugeinterface_MOD_gaugeinterface_evolvescal ()
#3  0x000055555559ca5d in __gaugeinterface_MOD_gaugeinterface_evolvescal ()
#4  0x00005555555cf4ef in __cambmain_MOD_cmbmain._omp_fn.4 ()
#5  0x00007ffff7877fc2 in ?? () from /usr/lib/libgomp.so.1
#6  0x00007ffff7dc3feb in ?? () from /lib/ld-musl-x86_64.so.1
#7  0x0000000000000000 in ?? ()
```

**Comment by cmbant** [comment]
Seems to work for me : 
https://hub.docker.com/r/cmbant/testdocker/builds/bjjts6egxgvghenjut5dufo/
(unless for some reason error is missing)

**Comment by marius311** [comment]
Odd, you're right, here I confirm the output files are created: https://hub.docker.com/r/marius311/testdocker/builds/bg48fxyu6dpxkuymmxvtncf/

I just tried building locally on a second system besides my laptop where I saw the initial error and there I get a segfault though. It must have something to do with the Docker version or some interaction with the host machine.
