### ISSUE TITLE
extrap_kmax option in get_matter_power_interpolator

### ISSUE THREAD

**Issue by MCostanzi** [cmbant/CAMB#29]
Hi,

I'm trying to use the option "extrap_kmax" with "get_matter_power_interpolator" but I get the error:

TypeError: get_matter_power_interpolator() got an unexpected keyword argument 'extrap_kmax'

Looking at the camb.py module it seems that indeed this parameter is not present in the definition of "get_matter_power_interpolator".
Actually the function "get_matter_power_interpolator" is not the same as the one shown in the wiki:
http://camb.readthedocs.io/en/latest/_modules/camb/camb.html#get_matter_power_interpolator

I'm using CAMB version: 0.1.6.1  (August 2017).

Thanks in advance.
Best,
Matteo Costanzi

**Comment by cmbant** [comment]
Make sure you are using the latest version from github

**Comment by MCostanzi** [comment]
I followed the link given in the email:
https://github.com/cmbant/CAMB/releases

and I have downloaded the August 2017 version (I've downloaded it today)

**Comment by cmbant** [comment]
The docs refer to the latest github version.

**Comment by MCostanzi** [comment]
This is the one I've donwloaded (it is labeled "Latest release)
![screenshot from 2018-03-08 18 32 16](https://user-images.githubusercontent.com/17427602/37167025-033d79ce-2301-11e8-91c6-abbcc1d2ecd0.png)

Is there a newest version?

**Comment by cmbant** [comment]
The docs refer to the current master branch, not the last release.

**Comment by MCostanzi** [comment]
I see...sorry for the misunderstanding
