### ISSUE TITLE
problem compiling on mac with ifort

### ISSUE THREAD

**Issue by earnric** [cmbant/CAMB#35]
I'm trying to build the latest version on my mac that has both ifort and gfortran (8). Since the setup file seems to find ifort, it is using that. I am getting the following error on the fortran part of the build.

> /Applications/Xcode.app/Contents/Developer/usr/bin/make -C Releaselib --no-print-directory -f../Makefile SRC_DIR=.. libforutils.a
> ifort -fpp -W0 -WB -fpic -qopenmp -gen-dep=.d -fp-model precise -W0 -WB -fpp -qopenmp -gen-dep=MiscUtils.d -fast -o MiscUtils.o -c ../MiscUtils.f90
> ifort: command line error: '-fminshared' conflicts with '-fpic'
> make[3]: *** [MiscUtils.o] Error 1
> make[2]: *** [directories] Error 2
> make[1]: *** [Releaselib] Error 2
> make: *** [libforutils_so] Error 2
> chmod: ../camb/camblib.so: No such file or directory
> Compilation failed

I've tried finding the -fminshared flag but it doesn't seem to exist in setup.py or the Makefile... ?

I'm not sure if this is a config problem on my system or a problem with the setup for ifort on macs.

**Comment by cmbant** [comment]
There are some suggestions here: 
https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/721055

I don’t use a Mac do if you could make a pull,request when it works that would be great.

**Comment by earnric** [comment]
Thanks Antony -- I'll try to get it working and do a pull once I have it.

Cheers!

Rick
________________________________

**Comment by cmbant** [comment]
Did you manage to get this working?

**Comment by earnric** [comment]
Not yet... I'll have to revisit once I get some more time ... likely later this month.

Sorry for the delay!

Rick
________________________________

**Comment by cmbant** [comment]
Hopefully fixed by https://github.com/cmbant/CAMB/pull/51

**Comment by earnric** [comment]
Verified. This compiled on my MacBook Pro, 2016 with Home-brew compilers and ifort compilers.
