### ISSUE TITLE
Inconsistent comparison between Transfer.kmax and maxkh

### ISSUE THREAD

**Issue by andreufont** [cmbant/CAMB#38]
In line 757 of results.py:

`if self.Params.Transfer.kmax < maxkh:`
that raises the following warning:
`logging.warning("get_matter_power_spectrum using larger k_max than input parameter Transfer.kmax")`

The comparison above is inconsistent, since Transfer.kmax has units of 1/Mpc, while maxkh has units of h/Mpc. 

PS: my request for camb v2.0 would be to favor 1/Mpc over h/Mpc, in my opinion it makes things unnecessarily complicated to talk about Mpc/h when not working at z=0.

**Comment by cmbant** [comment]
fixed in 55cc4b1f619e55e03b974906f599c0fb56c9153d

**Comment by andreufont** [comment]
Thanks!
