### ISSUE TITLE
camb.baseconfig.CAMBError: Error in Fortran called from calc_transfer

### ISSUE THREAD

**Issue by ziwenkk** [cmbant/CAMB#39]
when I try to use camb.1.0.4 with python2.7, it keeps informing me that

    self.calc_transfers(params, only_transfers=False)
  File "/home/ziwen/anaconda2/lib/python2.7/site-packages/camb/results.py", line 273, in calc_transfers
    config.check_global_error('calc_transfer')
  File "/home/ziwen/anaconda2/lib/python2.7/site-packages/camb/_config.py", line 49, in check_global_error
    raise CAMBError(reference + '%s' % err)
camb.baseconfig.CAMBError: Error in Fortran called from calc_transfer:
optical depth redshift finder did not converge

I used to use python3 , then I thought maybe this issue is caused by the version of python, but now I have switched to python2 , I got the same results . How should I fix it ？

**Comment by cmbant** [comment]
Please provide full code example to reproduce, thanks.

**Comment by ziwenkk** [comment]
[code&data.zip](https://github.com/cmbant/CAMB/files/3012902/code.data.zip)
Inside this zip  contains three files,one of them is the code file,the other two is data files. Thank you very much!

**Comment by cmbant** [comment]
Thanks, but I meant a simple few-line CAMB-only example. If it's happening in the middle of sampling it may be because you have crazy parameters (e.g. z_re > 50).

**Comment by ziwenkk** [comment]
You are right, I changed a few parameters, and the program worked out, thank you !
