### ISSUE TITLE
k, k**2, k*EV%kf(1)

### ISSUE THREAD

**Issue by gaby7646** [cmbant/CAMB#42]
Sorry if this is a very dumb question. If I understand k2=k**2. Sometimes when k2 appears in tequations_ppf.f90 also EV%kf(1) does. It is not clear for me when I should add EV%kf(1).
For example, what is the difference between: `sigma=(z+1.5_dl*dgq/k2)` and `sigma=(z+1.5_dl*dgq/k2)/EV%kf(1)`?
Or the difference between `k2, k*k, k2*EV%kf(1)`?

**Comment by cmbant** [comment]
Kf is the factor you need to account for curvature. In a flat universe it is 1.

**Comment by gaby7646** [comment]
Thanks for reply.
