### ISSUE TITLE
Halofit Neutrino

### ISSUE THREAD

**Issue by vivianmiranda** [cmbant/CAMB#44]
Dear Prof Lewis,

I am writing to inquire what the reference for the Neutrino Updates on Halofit Takahashi is. I am asking that because CAMB and CLASS differ in those updates. I attached the different term. Such difference did impact DES only chains, so I am trying to figure out where those updates originate. There is only a thank you comment to Prof. Bird

Best
Vivian

<img width="399" alt="Screen Shot 2019-07-02 at 4 56 42 PM" src="https://user-images.githubusercontent.com/3210728/60542473-69092c80-9cea-11e9-9181-aba1540030f7.png">

**Comment by cmbant** [comment]
I emailed Simeon Bird but didn't get a reply as yet.

**Comment by vivianmiranda** [comment]
Thank you

**Comment by alexander-mead** [comment]
For what it's worth, I am also interested in the answer to this. I saw the neutrino updates to the Takahashi et al. HALOFIT in the source code but I don't know of any reference for them.

**Comment by cmbant** [comment]
This was changed in https://github.com/cmbant/CAMB/commit/2807c452, with log comment "Halofit tweak to prevent negative values in neutrino models for high  Omega". It was from Simon Bird (private correspondence):

```
However, the effect of neutrinos in this simulation looks identical to
that at Omega_M = 0.3. I tried both:

fnu*(0.977-X*(omm0-0.3))

and:

fnu*(0.977+X*((omm0/0.3)**0.55-1))

Both had essentially the same chi-square, which is a bit odd.

The Omega_M = 0.4 run favours X=0, but the Omega_M = 0.25 run wants X
large and negative. These results seem inconsistent to me.

One thing I noticed was that the value of omega_baryon fed to CAMB was
0.05 for most simulations, but 0.04 with Omega_M = 0.25. This shouldn't
make any difference, but it makes me suspect that something else changed
in the simulation pipeline in between which messed things up.

I think the best idea is just to set X = 0. It is a small correction
which does seem to be actually zero between Omega_M = 0.3 and Omega_M =
0.4. Working hypothesis is that Omega_M = 0.25 is messed up somehow.
There was no significant effect in changing h, ns, or sigma_8, and it's
tough to think of a physical effect which really only appears for
Omega_M < 0.3.

So then the halofit line just reads:

fnu*0.977
```

**Comment by alexander-mead** [comment]
Further to this, are the parameter values for the Bird correction not different between the paper and the CAMB implementation? For example, the change to the HALOFIT gamma parameter in Bird et al. (2012) https://arxiv.org/pdf/1109.4416.pdf (equation A5) reads:
```
gamma -> gamma + 0.316 - 0.0765n - 0.835C
```
whereas the equivalent line in CAMB has no such modification to the HALOFIT gamma. Also, the line for beta in https://arxiv.org/pdf/1109.4416.pdf (equation A10) reads
```
beta -> beta + f_nu*(-6.49+1.44*n**2)
```
whereas in CAMB it is
```
beta -> beta + fnu*(1.081+0.395*n**2)
```
Also, equation (A6) in Bird et al. has a denominator with a y^3 term, but this seems to be missing in the CAMB implementation, as well as having different numbers compared to CAMB. Also the 47.48 in CAMB does not match the 26.3 in equation (A9).

I suppose these changes are a result of going from applying the Bird neutrino model to the original HALOFIT of Smith et al. to applying it to the updated Takahashi et al. model? Is there a reference for these changes? Not that I am complaining, I'm just curious.

**Comment by cmbant** [comment]
Probably best to ask Simeon about this; there were some changes noted in 2015.

**Comment by alexander-mead** [comment]
@sbird - would you be able to comment on this?

**Comment by sbird** [comment]
@alexander-mead is exactly correct: I re-fit the original simulations used in the paper using the Takahashi code as a base. 

The original changes to beta and gamma were an attempt to fix the known issue of Smith halofit at high k by changing the mnu = 0 model. Since Takahashi fixes that using a larger base of simulations, I figured that it would be more accurate to use their mnu = 0 model and only add my changes for mnu > 0. But since the base changed, the new fitting coefficients also changed with them. I should still have the original power spectra if you want to do the fit yourself.

PS Antony, I do apologise but I never received your July email. Probably I should have fixed the CLASS sources at the same time as fixing CAMB. Did someone do that already?

**Comment by cmbant** [comment]
You mean from July 2019? Not sure what's happening with CLASS, I'm not following it.

**Comment by sbird** [comment]
Yup, from July 2019.

**Comment by sbird** [comment]
I uploaded the raw data and fitting code here: https://github.com/sbird/numatpowscripts It is very old code and may not work, but you can certainly look at it.

**Comment by alexander-mead** [comment]
@sbird I certainly had no plans to do any refitting. I was just curious as to why the numbers were different and to where I should point my citations. 

For me, this is all cleared up now.
