### ISSUE TITLE
Running tests locally

### ISSUE THREAD

**Issue by alexander-mead** [cmbant/CAMB#47]
Is still a way of running tests locally? Or is the only way to initiate a pull request and have that run the full set of Travis tests? I think prior to the v1 release there were tests that could be run locally. I tried `python camb_tests/camb_test.py`, but that didn't seem to do anything.

**Comment by cmbant** [comment]
Yes. In PyCharm I can right-click on camb_tests and select "Run Nose tests.." to do python tests (also "python setup.py test" should work). Running fortran tests is more complicated, but could be done locally using similar commands to the travis test: https://github.com/cmbant/CAMB/blob/master/fortran/tests/run_tests.sh

**Comment by alexander-mead** [comment]
Okay `python setup.py test` worked for me. I briefly tried to run the Fortran tests following the commands in the `run_tests.sh` script but couldn't figure it out. I resorted to making a pull request and letting that run the tests. If anyone comes up with a snappy command to run the Fortran tests from the command line then I would love to know it.

**Comment by cmbant** [comment]
What didn't work? Should just need the CAMB_test_files commands (only need to clone the reference comparison files once).
However, personally I almost always use test branches in travis myself.
