### ISSUE TITLE
Python compile when doing development

### ISSUE THREAD

**Issue by alexander-mead** [cmbant/CAMB#49]
I am modifying one of the .f90 files. When I want to test my modifications I run `python setup.py install` from the `camb` directory. I got stuck a couple of times because I had introduced a bug into the Fortran code, and that file didn't compile, but then the rest of the python install completed normally (I guess using old versions of .mod files, but I don't know). I had to scroll quite a way up the output of `python setup.py install` to see that compiling the Fortran file had actually failed.

Would it be possible to change the python install so that it exits if it doesn't successfully compile all the Fortran code? Or is my development workflow wrong somehow?

**Comment by cmbant** [comment]
I use python setup.py make, which just builds the Fortran (assuming you installed with pip install -e, you don't need to do anything else to update the build after changes).

**Comment by alexander-mead** [comment]
Okay, great. The combination of `pip install -e .` followed by `python setup.py make` works for me when updating the Fortran, and also allows me to see if the Fortran code didn't compile properly.
