### ISSUE TITLE
Errors in CAMB kill the python process

### ISSUE THREAD

**Issue by tilmantroester** [cmbant/CAMB#54]
At the moment, errors in the Fortran code are dealt with by calling `STOP` or `ERROR STOP`, which kills the process. When using CAMB as part of a bigger python application, such as sampling a likelihood or even just within a jupyter notebook, this behaviour is problematic since it can't be caught from within python.

For example, trying to sample low values of `omch2` with high values of `w` causes an `Integration timed out` error in HMCode, which kills the process calling CAMB. MWE:
```python
import camb

p = camb.CAMBparams(WantTransfer=True, NonLinearModel=camb.nonlinear.Halofit(halofit_version="mead"))
p.set_cosmology(H0=70.0, omch2=0.04, ombh2=0.022, mnu=0.06)
p.set_dark_energy(w=-0.1)
p.set_matter_power(kmax=10.0, nonlinear=True)

r = camb.get_results(p)

k, z, pofk = r.get_nonlinear_matter_power_spectrum()

print("Finished without crash!", flush=True)
```

The offending integral in the above example is https://github.com/cmbant/CAMB/blob/0fc9020302a70354b512b1376e879caaf292221b/fortran/halofit.f90#L2093
Should I open a separate issue for this? @alexander-mead

**Comment by cmbant** [comment]
That specific thing does look like a separate (new?) issue from recent halofit changes.

More generally, there is no exception handling in Fortran, so AFAIK there's no general way to handle errors cleanly. Most other errors are already recovered cleanly with an error message return (using global error variables in the fortran).  But if you need all failures to be caught recoverably, the best thing is to use a separate process, e.g. see how validate_ini_file works in camb.py.

**Comment by tilmantroester** [comment]
I'm mostly concerned about the cases where the sampler encounters a part of the parameter space that causes a crash hours into the run. Most of the `STOP` statements that don't seem to be related to configuration settings are in `halofit.f90`. To avoid the crashes, would replacing the `STOP` statement with a `call GlobalError()` and a `return` be sufficient?

**Comment by cmbant** [comment]
Yes, it should be (also testing the global error value if the error is within nested subfunctions, and making sure you don't introduce memory leaks)

**Comment by cmbant** [comment]
In https://github.com/cmbant/CAMB/commit/0e48773c39900fc3c76f4be1f83c90786cd7ab95 I tried to propagate HMCode errors into python exceptions. Your example will now raise an exception (however it will be very slow: w=-0.1 with H0=70 is so far off anything allowed you may want to exclude it using a tighter prior)
