### ISSUE TITLE
two problems when running the debug version

### ISSUE THREAD

**Issue by terryys** [cmbant/CAMB#58]
These two problems occurs when running the program with debug option when compiling.

The first problem is in GaugeInterface_EvolveScal in equations.f90, the if condition just under the comment "!Mass starts to become important, start evolving next momentum mode". The second condition will give an array out of bound error if the number of neutrino mass eigenstates is larger than 1.

The second problem occurs in cosmomc when calling CAMBparams_SetNeutrinoHierarchy. The lower bound when finding the root in the inverted case will cause a division by zero error.

To fix the first bug, the condition can be split into two and add one more layer of if. To fix the second bug, a small number can be added to the lower bound like sqrt(delta_mnu31)+1e-6_dl.

**Comment by cmbant** [comment]
Thanks, merged https://github.com/cmbant/CAMB/pull/59
