### ISSUE TITLE
"Assuming arrays in order" errors when using via CosmoMC with DES and nested sampling 

### ISSUE THREAD

**Issue by williamjameshandley** [cmbant/CAMB#60]
Hi @cmbant 

Have there been any significant changes to the code recently that might affect the DES likelihood? When using [nested sampling](https://github.com/williamjameshandley/CosmoChord) with the latest updates to cosmomc and camb, I'm finding that runs terminate with 
```
Assuming arrays in order
```
when using just the `batch3/DES.ini` likelihood. The error occurs only a little way into nested sampling, indicating that it's an issue that occurs in the tail, but unfortunately is also a pretty rare issue, since it only arises after ~ 25,000 likelihood calls

It appears this arises from `camb/fortran/halofit.f90`, but I'm not sure (a) why this error has arisen recently when previously it did not, and (b) what is the most appropriate way to fix it.

I'm happy to make a PR, but felt it best to seek your advice as to the most likely cause of the issue before going code diving. 

The most immediate solution would be to replace the `stop` errors with the new `GlobalError` calls that have arisen in recent updates, but this doesn't explain why this error might be occurring, and it would be good to know that this isn't something more insidious before masking the issue by just logzeroing the problem.

**Comment by cmbant** [comment]
It's probably from recent HMCode changes. I guess the issue is one of the tables has zero step width or is not in order for some reason; I don't supposed you figured out which table it was searching in or know the relevant parameters?

**Comment by cmbant** [comment]
Ping transfer to CAMB @williamjameshandley

**Comment by cmbant** [comment]
I've converted the error into a global error that can be ignored. It should write out some values when it happens to help track why it happens, please report if you see them.

**Comment by williamjameshandley** [comment]
Many thanks @cmbant. I've merged those latest changes into [CosmoChord](https://github.com/williamjameshandley/CosmoChord) and [the nested sampling version of camb](https://github.com/williamjameshandley/CAMB)
