### ISSUE TITLE
Neff is ignored when there are no massive neutrinos

### ISSUE THREAD

**Issue by tilmantroester** [cmbant/CAMB#63]
Currently the `nnu` option in `CAMBParams.set_cosmology` is ignored when `omnuh2` is zero (due to mnu = 0 or num_massive_neutrinos = 0) and requires manually assigning `CAMBParams.num_nu_massless`.

MWE:
```python
import camb
import numpy as np

Neff = 2.5

p = camb.CAMBparams()
p.set_cosmology(ombh2=0.022, omch2=0.11, H0=70.0, nnu=Neff, 
                num_massive_neutrinos=0,
                mnu=0.0)
# Fails
assert np.isclose(Neff, p.N_eff)

# Works
p.num_nu_massless = Neff
assert np.isclose(Neff, p.N_eff)
```

**Comment by cmbant** [comment]
Thanks, your fixhttps://github.com/cmbant/CAMB/pull/64 looks fine.
