### ISSUE TITLE
integration timed out with a set of parameters

### ISSUE THREAD

**Issue by terryys** [cmbant/CAMB#65]
This is related the cmbant/CosmoMC#27. A set of parameters can cause an integration timed out error in CAMB. The corresponding parameter file is attached. The latest commit gives "HMCode INTEGRATE, Integration timed out" when run with the attached parameter file. I have checked earlier commits and 69e577a3d4df959e9140ee18bf80b1da3e0e9c21 gives "INTEGRATE: Integration timed out" instead.
[debug.txt](https://github.com/cmbant/CAMB/files/3828624/debug.txt)

**Comment by cmbant** [comment]
Thanks for the test case, please try https://github.com/cmbant/CAMB/commit/e07428e291442f9af4cd406bb757bf9bb7fc7c1b.
Seems like the background integration is differing very slightly from the evolution when evolving the perturbations.
