### ISSUE TITLE
Problem in python when setting an initial condition vector

### ISSUE THREAD

**Issue by SamuelBrieden** [cmbant/CAMB#67]
I get an error in CAMB if I want to compute the power spectrum for more than 1 initial condition at the same time. In that case, if I understand correctly, the procedure is to pass the string `"initial_vector"` to the `CambParams` instance `"scalar_initial_condition"`. However, in the python wrapper that choice corresponds to the value '6', while in the fortran code it is '0'. So I guess this can easily be changed by putting `"start"=0` and pulling `"initial_vector"` to the front instead of having
`("scalar_initial_condition", c_int,
         {"start": 1, "names": ["initial_adiabatic", "initial_iso_CDM", "initial_iso_baryon",
                                "initial_iso_neutrino", "initial_iso_neutrino_vel", "initial_vector"]}),`

**Comment by cmbant** [comment]
Thanks, fixed in https://github.com/cmbant/CAMB/commit/46a7e681b2544120c2192e60e87a0020867726f0
