### ISSUE TITLE
Anaconda installation instructions feedback

### ISSUE THREAD

**Issue by didamarkovic** [cmbant/CAMB#68]
Hi, this is a minor comment about the [installation instructions](https://github.com/cmbant/CAMB/blob/master/docs/source/index.rst). 
The suggested command: `conda install -c conda-forge camb` only installs CAMB, but not Pycamb. Perhaps it would be clearer to add ` pycamb` into that command (as is suggested on the [Conda Feedstock page](https://github.com/conda-forge/camb-feedstock)).

**Comment by cmbant** [comment]
I think the pycamb package is just for compatibility with old install programs, conda installing camb should give everything you need? (nothing is called "pycamb" since version 1.x)

**Comment by didamarkovic** [comment]
I tried doing that but that didn’t install the camb.py or place anything into the Anaconda site-packages. I tried this today on a Mac with Anaconda installed last week.

**Comment by cmbant** [comment]
You don't need "camb.py" - the command line script is just called "camb". Does that and "import camb" not work?

**Comment by cmbant** [comment]
Can you uninstall and then show the full output for this?

```
conda install -c conda-forge camb
python -c "import camb"

```

**Comment by didamarkovic** [comment]
```
didamarkovic$ conda install -c conda-forge camb
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/markovic/opt/anaconda3

  added / updated specs:
    - camb


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.9.11          |           py37_0         147 KB  conda-forge
    conda-4.7.12               |           py37_0         3.0 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.1 MB

The following NEW packages will be INSTALLED:

  camb               conda-forge/osx-64::camb-0.1.8.1-hdc02c5d_1002

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                         pkgs/main --> conda-forge
  conda                                           pkgs/main --> conda-forge


Proceed ([y]/n)? y


Downloading and Extracting Packages
certifi-2019.9.11    | 147 KB    | ####################################################################################### | 100% 
conda-4.7.12         | 3.0 MB    | ####################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
didamarkovic$
didamarkovic$
didamarkovic$ python -c "import camb"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'camb'`

**Comment by cmbant** [comment]
Looks like it installed an old pre-1.0 version, probably related to the errors at the top. Try  this

`conda install -c conda-forge "camb>=1"`

If that doesn't work, try making a new clean environment using
 `conda create -n py37forge -c conda-forge python=3.7 scipy pandas matplotlib
`
and then conda install in that.

**Comment by didamarkovic** [comment]
The new environment worked. It seems like I have conflicts. Sorry to have bothered you. You wouldn't have thought you'd have conflicts on a brand new computer. CAMB was the third package I installed.

**Comment by Alkistis** [comment]
Hi both! Glad I checked the closed issues and found this...I was struggling with the same problem in a new computer. The new environment works. Cheers :-)
