### ISSUE TITLE
Segfault when doing sources and tensors

### ISSUE THREAD

**Issue by mraveri** [cmbant/CAMB#70]
I am trying to compute both number counts/lensing sources and the tensor spectra.
Just changing get_tensor_cls = T in params_lensing.ini triggers a segfault at line 1717 of results.f90.

I think this is because the window functions are not allocated for tensors.

**Comment by cmbant** [comment]
Thanks - but that line looks blank, not master?
https://github.com/cmbant/CAMB/blob/master/fortran/results.f90#L1717

**Comment by mraveri** [comment]
Right, sorry, I had another branch in mind! The line on master is 1638

**Comment by mraveri** [comment]
Just opened a PR to solve the problem #71 
This initializes the window functions for scalar vector and tensors (which is possibly overkill).
The redundant initialization might be solved by passing the calling_again flag to initialization.

**Comment by cmbant** [comment]
Hopefully now fixed in https://github.com/cmbant/CAMB/commit/39404bd97fc54a85b73f8ab9d2592078c95102c9

**Comment by mraveri** [comment]
Works perfectly! Thanks!
