### ISSUE TITLE
Mistake in DarkEnergyFluid.validate_params test

### ISSUE THREAD

**Issue by joezuntz** [cmbant/CAMB#73]
Hi Antony,

I think there's a typo in the test in `DarkEnergyFluid.validate_params` that means that sometimes it doesn't trigger an error in the right situation, and the parameters can get through to the fortran layer and cause a `STOP`.  

It's this line:
https://github.com/cmbant/CAMB/blob/08341cdbf48b4a354486d2d5e1941f1f8bba1a08/camb/dark_energy.py#L82

which should presumably match this line:
https://github.com/cmbant/CAMB/blob/3bdc644b352c9049f5bbf3d813141c2fd9ca6571/fortran/DarkEnergyFluid.f90#L87

but is off by 1 in the second clause.

Cheers,
Joe

**Comment by cmbant** [comment]
Thanks, should be fixed in https://github.com/cmbant/CAMB/commit/64d17516bc18dea8b361a9faa10efa920e37298b
