### ISSUE TITLE
Modify current time

### ISSUE THREAD

**Issue by hippke** [cmbant/CAMB#74]
Thank you for this fantastic package!
I like to calculate the CMB power spectrum for a time different to now (e.g., late universe).
This was done e.g. by [Zibin et al. (2007)](https://arxiv.org/pdf/0706.4482.pdf) who *"change the `tau0` variable to trick the code into using a different observational time"*. Given that 13 years have passed, is this still the right way to do it? If yes, should it be done on the Fortran side or the Python side? I see that `tau0` is touched 119 times across 9 source code files in the repository. But I can not immediately see where and how to change its value. Ideally, it would be great to put this in the config ini file.
Thank you for your help!

**Comment by cmbant** [comment]
For the time of interest, I think you just need to work out what H0 and TCMB will be at that time, and then use those as input parameters to CAMB.

**Comment by hippke** [comment]
Thank you for the advice. This works partly. OK:
```
import camb
pars = camb.CAMBparams()
pars.set_cosmology(H0=65, TCMB=1.5)
results = camb.get_results(pars)
```
But when I change to lower values e.g. `TCMB=1.49`, I get a `binary_search (e.g for optical depth) did not converge` no matter what `H0` I set. 
Any ideas?

**Comment by cmbant** [comment]
You would need to also change tau for full consistency. Are your H0 and TCMB values definitely consistent with the same cosmology?
