### ISSUE TITLE
python setup.py make

### ISSUE THREAD

**Issue by gaby7646** [cmbant/CAMB#82]
Hi, I've already installed fortran camb without issues. And now I'm trying to install camb to run the CAMBdemo.ipynb from a linux machine and when I type: `python setup.py make` I obtain the following error: 
`File "setup.py", line 19
    _compile: Any = __import__('_compilers')
SyntaxError: invalid syntax`
I'll be very grateful for your help.

**Comment by cmbant** [comment]
What was the actual error message? (Check using. Python 3)

**Comment by gaby7646** [comment]
Thanks Anthony, the error was. `SintaxError: invalid syntax` but now I did what you suggest `python3 setup.py make` succesfully.

**Comment by Chris-Pedersen** [comment]
Hi @cmbant , is there a Python verison requirement here? I get the same error:

```
~/Codes/CAMB$ python3 setup.py make
  File "setup.py", line 19
    _compile: Any = __import__('_compilers')
            ^
SyntaxError: invalid syntax
```

when running on Python 3.5.2

**Comment by cmbant** [comment]
You need at least 3.6
