### ISSUE TITLE
Need help getting a specific transfer function from CAMB

### ISSUE THREAD

**Issue by JavierZhao** [cmbant/CAMB#84]
Hi, I'm interested in getting the quadrupole transfer function Delta_two in equation (3) of the following paper:[https://arxiv.org/abs/astro-ph/0603271]. 

Specifically, I want to get a value for Delta_two when given an input tuple (k,r). The code in code block 18 and 19 in CAMBdemo.html seems most relevant, but those functions do not accept input of redshift values. 

Can anyone show me how to achieve this with CAMB? Thanks in advance!

**Comment by cmbant** [comment]
You can change the accuracy parameters to adjust sampling, and spline if needed.
You can also get the photon quadrupole and other transfer functions as a function of k and time (pi_photon, see box 26+ in demo).
