### ISSUE TITLE
Unlensed Cl BB zero from ell = 600 onwards, with tensors

### ISSUE THREAD

**Issue by 1cosmologist** [cmbant/CAMB#87]
Running CAMB v 1.1.3 in python script.
For r=0.05, ell > 600, unlensed total ClBB is zero.
Parameters set:

planck18 = cm.model.CAMBparams(
    WantCls = True,
    WantScalars = True,
    WantTensors = True,
    Want_CMB = True,
    Want_CMB_lensing = False
)

accuracy_settings = cm.model.AccuracyParams(
    AccuracyBoost=2., 
    lSampleBoost=50., 
    lAccuracyBoost=3.,
    AccuratePolarization = True, # Do you care about the accuracy of the polarization Cls?
    AccurateBB = True,           # Do you care about BB accuracy (e.g. in lensing)
    AccurateReionization = True  # Do you care about pecent level accuracy on EE signal from reionization?
)

planck18.set_for_lmax(
    lmax_camb, 
    max_eta_k=None, 
    lens_potential_accuracy=1., 
    lens_margin=lens_acc_till, 
    k_eta_fac=2.5, 
    lens_k_eta_reference=18000.0
)

planck18.set_cosmology(
    H0=67.66, 
    ombh2=0.02242, 
    omch2=0.11933, 
    omk=0.0, 
    YHe=0.2454, 
    TCMB=2.7255, 
    tau=0.0561 
    # zrei=7.82
)

P_k_primordial = cm.initialpower.InitialPowerLaw(
    parameterization = 2, #'tensor_param_rpivot',
    ns = 0.9665,
    r = r,
    pivot_scalar = 0.05,
    pivot_tensor = 0.05,
    As = 2.105e-9 
)
![unlensed-tensorBB](https://user-images.githubusercontent.com/11816582/91961578-ef316080-ed3d-11ea-9b4b-3f88afbe1c54.png)

**Comment by cmbant** [comment]
Doesn't sound like a bug - what's your CAMBparams.max_l_tensor?
