### ISSUE TITLE
get_time_evolution fails with symbolic variables when two CAMBdata instances present

### ISSUE THREAD

**Issue by ahallcosmo** [cmbant/CAMB#92]
The following code gives a seg fault (CAMB v1.1.2, Sympy v1.5.1) when calling CAMB_TimeEvolution in get_time_evolution (results.py).

```python
import camb
from camb.symbolic import *

pars_A = camb.set_params(H0=67., ombh2=0.022, omch2=0.12, tau=0.05,
                As=2.1e-9, ns=0.96, lmax=2500)

pars_B = camb.set_params(H0=68., ombh2=0.022, omch2=0.12, tau=0.05,
                As=2.1e-9, ns=0.96, lmax=2500)

data_A = camb.get_results(pars_A)
data_B = camb.get_results(pars_B)

monopole_source, ISW, doppler, quadrupole_source = get_scalar_temperature_sources()

k = 0.03
z = 1090.

T_A = data_A.get_redshift_evolution(k, z, [monopole_source])
```

Everything works fine if data_B.get_redshift_evolution is called instead of data_A, hinting at some memory conflict somewhere. Weirdly it works if a non-symbolic variable, e.g. 'delta_photon' is passed rather than monopole_source in this example.

**Comment by cmbant** [comment]
Try https://github.com/cmbant/CAMB/commit/05f97477be48fa15e9dbf552fe66a3351d61543b ?

**Comment by ahallcosmo** [comment]
Yes these seems to have fixed it! Cheers
