### ISSUE TITLE
How to add new paraemter?

### ISSUE THREAD

**Issue by YutoMinami** [cmbant/CAMB#94]
I tried to add one new parameter to InitialPower.f90, like `  real(dl) :: r_vac = 0._dl`  at the line after  `real(dl), private :: curv = 0._dl`. 
This works well for the binary camb when I ran like `camb params.ini`.
To extend this to python, I also added the parameter as `  ("r_ast", c_double),`in `class InitialPowerLaw(InitialPower)'` at the line after the ` ("At", c_double),` and similarly add the parameter to the argument of the member function `def set_params`.
When I ran the code via python, the parameter set in python interface never changed.
I checked it with write(\*,\*) function in cmbmain.f90. I found that the originally implemented parameter, like ns, can be changed, although the variable I implemented, r_vac, cannnot be changed. 
Are there any additional treatments to connect python to fortran?
For the compilation, I follow the README as
> python setup.py make
> pip install -e .

**Comment by cmbant** [comment]
If it's immediately after A_t in python it needs to be immediately after A_t in fortran.
(you can also just use a function defined in Python, without modifying fortran, as demonstratd in the example notebook)

**Comment by YutoMinami** [comment]
Thank you very much. That solved the issue.
I assumed that I should not disturb the initial implemented parameter after `At`, `real(dl), private :: curv = 0._dl !curvature parameter`.

(Yes, I finally realised that I should have calculated it in python... I modified fortran file because I got the modification from my collaborator who have  used only fortran.)
