### ISSUE TITLE
gfortran 10 error with MatrixUtils.f90

### ISSUE THREAD

**Issue by alexander-mead** [cmbant/CAMB#96]
I recently upgraded to `gfortran 10` (maybe this was a mistake). I installed this using `homebrew` on Mac with the latest Big Sur OS upgrade (`brew install gcc`; and I now have `gcc 10.2.0`).

I get a new error when I do `make` in `CAMB/fortran`:

```
gfortran -cpp -ffree-line-length-none -fmax-errors=4 -MMD -fopenmp -fPIC -O3 -ffast-math -o MatrixUtils.o -c ../MatrixUtils.f90
../MatrixUtils.f90:1733:49:

 1726 |         call DGESDD('O',m,n, Mat, m ,D,U,m,Mat,n,OptWk,WorkSize,IWork,ierr)
      |                                                 2
......
 1733 |         call DGESDD('O',m,n, Mat, m ,D,U,m,Mat,n,rv1,WorkSize,IWork,ierr)
      |                                                 1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
make[3]: *** [MatrixUtils.o] Error 1
make[2]: *** [directories] Error 2
make[1]: *** [Release] Error 2
make: *** [libforutils] Error 2
```

I think this is related to `OptWk` being a scalar at `1726` and then `rv1` being an array at `1733`.

**Comment by cmbant** [comment]
optWk is also an array (of size 1)? - looks like a possible issue in the diagnostics. The tests run on gfortran 11 trunk which works OK, though the gfortran 10 builds currently fail due to inconsistent OPENMP libs on ubuntu toolchain test.
Does it work if you change OptWk to be rv1 allocated to size 1, then reallocated after?

**Comment by cmbant** [comment]
PS. if your forutils version code the same as https://github.com/cmbant/forutils/blob/master/MatrixUtils.f90#L1701 ?

**Comment by alexander-mead** [comment]
Pulling the most recent `forutils` solved the problem. Sorry for the trouble. I'll close this. I am now seeing the same `ld: library not found for -lSystem` error as in #97 though, but I don't think that this is `CAMB` specific.
